version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    build-maven:
        depends_on:
            - consul
        image: bhuisgen/alpine-build-maven
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - CONSUL_AGENT=consul                                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/                            # consul key prefix path
            #- BUILD_GITURL=git@git.my.domain:your/project.git          # git repository URL
            #- BUILD_GITREF=HEAD                                        # git tag/commit reference to build
            #- BUILD_PROJECT=                                           # project directory (empty for the root of sources)
            #- BUILD_SCRIPT=/usr/local/build/build.sh                   # build script
            #- BUILD_TIMEOUT=3600                                       # build timeout
            #- MVN_OPTIONS=                                             # maven options
            #- MVN_GOAL=test                                            # maven goal
