version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    zabbix-server:
        depends_on:
            - consul
        image: bhuisgen/alpine-zabbix-server-pgsql
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /host/data:/var/lib/zabbix       # volume for data
        environment:
            - CONSUL_AGENT=consul               # consul agent hostname/IP
            #- CONSUL_PORT=8500                 # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/    # consul key prefix path
            - CONSUL_SERVICENAME=zabbix-server  # consul service name
            - CONSUL_SERVICETAGS=dev            # consul service tag
            - CONSUL_SERVICEPORT=10051          # consul service port
            - CONSUL_CHECKTYPE=tcp              # consul health check type
            - ZABBIX_DBHOST=mysql               # database host
            - ZABBIX_DBPORT=3306                # database port
            - ZABBIX_DBNAME=zabbix              # database name
            - ZABBIX_DBUSER=zabbix              # database user
            - ZABBIX_DBPASSWORD=zabbix          # database password
            #- ZABBIX_STARTPOLLERS=5            # number of instances for pollers
            #- ZABBIX_STARTIPMIPOLLERS=0        # number of instances for IPMI pollers
            #- ZABBIX_STARTPOLLERSUNREACHABLE=1 # number of instances for unreachable hosts
            #- ZABBIX_STARTTRAPPERS=5           # number of instances for trappers
            #- ZABBIX_STARTPINGERS=1            # number of instances for ICMP pingers
            #- ZABBIX_STARTDISCOVERERS=1        # number of instances for hosts discovers
            #- ZABBIX_STARTHTTPPOLLERS=1        # number of instances for HTTP pollers
            #- ZABBIX_STARTTIMERS=1             # number of instances for time-base triggers and maintenance periods
            #- ZABBIX_STARTESCALATORS=1         # number of instances for escalators
            #- ZABBIX_JAVAGATEWAY=              # Java gateway IP
            #- ZABBIX_JAVAGATEWAYPORT=10052     # Java gateway port
            #- ZABBIX_STARTJAVAPOLLERS=0        # number of instances for Java pollers
            #- ZABBIX_STARTSNMPTRAPPER=0        # enable SNMP trapper
            #- ZABBIX_HOUSEKEEPINGFREQUENCY=1   # housekeeping frequency
            #- ZABBIX_MAXHOUSEKEEPERDELETE=5000 # maximum housekeeper tasks to delete
            #- ZABBIX_SENDERFREQUENCY=30        # unsent alerts retry frequency
            #- ZABBIX_CACHESIZE=8M              # cache size
            #- ZABBIX_CACHEUPDATEFREQUENCY=60   # cache update frequency
            #- ZABBIX_STARTDBSYNCERS=4          # number of instances for database syncers
            #- ZABBIX_HISTORYCACHESIZE=16M      # history cache size
            #- ZABBIX_HISTORYINDEXCACHESIZE=4M  # history index cache size
            #- ZABBIX_TRENDCACHESIZE=4M         # trend cache size
            #- ZABBIX_VALUECACHESIZE=8M         # value cache size
            #- ZABBIX_TIMEOUT=3                 # timeout of processing agent, SNMP and external checks
            #- ZABBIX_TRAPPERTIMEOUT=300        # timeout of processing trappers data
            #- ZABBIX_UNREACHABLEPERIOD=45      # period before setting host to unreachable
            #- ZABBIX_UNAVAILABLEDELAY=60       # delay before setting unreachable host to unavailable
            #- ZABBIX_UNREACHABLEDELAY=15       # delay to check unreachable host availability
            #- ZABBIX_LOGSLOWQUERIES=0          # log queries (query time)
            #- ZABBIX_STARTPROXYPOLLERS=1       # number of instances of proxy pollers
            #- ZABBIX_PROXYCONFIGFREQUENCY=1    # frequency to send configuration data to proxies
            #- ZABBIX_PROXYDATAFREQUENCY=1      # frequency to request history data from proxies
